/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_v1_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/ai-correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Ai Correction */
        post: operations["run_ai_correction_api_v1_jobs__job_id__ai_correction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/corrections/{patch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Decide Correction */
        patch: operations["decide_correction_api_v1_jobs__job_id__corrections__patch_id__patch"];
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_jobs__job_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/exports/{export_format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Document */
        get: operations["export_document_api_v1_jobs__job_id__exports__export_format__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/pages/{page_number}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Image */
        get: operations["get_page_image_api_v1_jobs__job_id__pages__page_number__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Samples */
        get: operations["list_samples_api_v1_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/samples/{sample_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sample Preview */
        get: operations["sample_preview_api_v1_samples__sample_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIRunRequest */
        AIRunRequest: {
            /** Api Key */
            api_key?: string | null;
            /**
             * Provider
             * @default openai_compatible
             * @enum {string}
             */
            provider: "gemini" | "openai_compatible";
        };
        /** AIRunResponse */
        AIRunResponse: {
            /** Job Revision */
            job_revision: number;
            /** Patches */
            patches: components["schemas"]["CorrectionPatch"][];
            /** Remaining Hosted Documents */
            remaining_hosted_documents: number | null;
        };
        /**
         * BlockKind
         * @enum {string}
         */
        BlockKind: "heading" | "paragraph" | "list_item" | "table" | "unknown";
        /** Body_create_job_api_v1_jobs_post */
        Body_create_job_api_v1_jobs_post: {
            /** File */
            file?: string | null;
            /** Sample Id */
            sample_id?: string | null;
        };
        /** BoundingBox */
        BoundingBox: {
            /** Height */
            height: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** CanonicalDocument */
        CanonicalDocument: {
            /** Corrections */
            corrections?: components["schemas"]["CorrectionPatch"][];
            /** Job Id */
            job_id: string;
            /** Pages */
            pages: components["schemas"]["DocumentPage"][];
            report?: components["schemas"]["IntelligenceReport"] | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
            /** Source Name */
            source_name: string;
        };
        /** Capabilities */
        Capabilities: {
            /** Accepted Media Types */
            accepted_media_types: string[];
            /** Artifact Ttl Seconds */
            artifact_ttl_seconds: number;
            /** Byok Providers */
            byok_providers: string[];
            hosted_provider: components["schemas"]["HostedProviderCapabilities"];
            /** Max Pdf Pages */
            max_pdf_pages: number;
            /** Max Upload Bytes */
            max_upload_bytes: number;
        };
        /** CorrectionDecision */
        CorrectionDecision: {
            status: components["schemas"]["CorrectionStatus"];
        };
        /** CorrectionPatch */
        CorrectionPatch: {
            /** Block Id */
            block_id: string;
            /** Id */
            id: string;
            /** Model Confidence */
            model_confidence: number;
            /** Original Text */
            original_text: string;
            /** Rationale */
            rationale: string;
            /** Replacement Text */
            replacement_text: string;
            /** Span Ids */
            span_ids: string[];
            /** @default proposed */
            status: components["schemas"]["CorrectionStatus"];
        };
        /** CorrectionResponse */
        CorrectionResponse: {
            /** Derived Text */
            derived_text: string;
            /** Job Revision */
            job_revision: number;
            patch: components["schemas"]["CorrectionPatch"];
        };
        /**
         * CorrectionStatus
         * @enum {string}
         */
        CorrectionStatus: "proposed" | "accepted" | "rejected";
        /** DocumentBlock */
        DocumentBlock: {
            bbox: components["schemas"]["BoundingBox"];
            /** Confidence */
            confidence: number;
            /** Id */
            id: string;
            kind: components["schemas"]["BlockKind"];
            /** Page Number */
            page_number: number;
            /** Raw Text */
            raw_text: string;
            /** Span Ids */
            span_ids: string[];
        };
        /** DocumentPage */
        DocumentPage: {
            /** Blocks */
            blocks: components["schemas"]["DocumentBlock"][];
            /** Height */
            height: number;
            /** Number */
            number: number;
            /** Spans */
            spans: components["schemas"]["OCRSpan"][];
            /** Width */
            width: number;
        };
        /** EvaluationAggregate */
        EvaluationAggregate: {
            corrected?: components["schemas"]["EvaluationMetrics"] | null;
            raw: components["schemas"]["EvaluationMetrics"];
        };
        /** EvaluationDiff */
        EvaluationDiff: {
            /** Corrected */
            corrected: string;
            /**
             * Label
             * @enum {string}
             */
            label: "improvement" | "regression" | "unchanged";
            /** Original */
            original: string;
        };
        /** EvaluationMetrics */
        EvaluationMetrics: {
            /** Cer */
            cer: number;
            /** Wer */
            wer: number;
        };
        /** EvaluationSample */
        EvaluationSample: {
            corrected?: components["schemas"]["EvaluationMetrics"] | null;
            /** Correction Count */
            correction_count: number;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Id */
            id: string;
            /** Labels */
            labels?: string[];
            /** Page Count */
            page_count: number;
            raw: components["schemas"]["EvaluationMetrics"];
            /** Representative Diffs */
            representative_diffs?: components["schemas"]["EvaluationDiff"][];
            /** Title */
            title: string;
        };
        /** ExtractedEntity */
        ExtractedEntity: {
            /** Citations */
            citations: components["schemas"]["ReportCitation"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "person" | "organization" | "date" | "money" | "location" | "identifier";
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostedProviderCapabilities */
        HostedProviderCapabilities: {
            /** Enabled */
            enabled: boolean;
            /** Remaining Documents */
            remaining_documents: number;
            /** Reset At */
            reset_at: string | null;
        };
        /** IntelligenceItem */
        IntelligenceItem: {
            /** Citations */
            citations: components["schemas"]["ReportCitation"][];
            /** Text */
            text: string;
        };
        /** IntelligenceReport */
        IntelligenceReport: {
            /** Entities */
            entities?: components["schemas"]["ExtractedEntity"][];
            /** Key Points */
            key_points?: components["schemas"]["IntelligenceItem"][];
            summary: components["schemas"]["IntelligenceItem"];
            /** Warnings */
            warnings?: string[];
        };
        /** JobResponse */
        JobResponse: {
            /** Artifact Keys */
            artifact_keys: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Page */
            current_page: number | null;
            /** Document Url */
            document_url: string;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Events Url */
            events_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Id */
            id: string;
            /** Progress */
            progress: number;
            /** Revision */
            revision: number;
            /** Source Name */
            source_name: string;
            stage: components["schemas"]["JobStage"];
            /** Status Url */
            status_url: string;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * JobStage
         * @enum {string}
         */
        JobStage: "queued" | "rendering" | "preprocessing" | "ocr" | "correction" | "awaiting_byok" | "intelligence" | "exports" | "complete" | "failed";
        /** OCRSpan */
        OCRSpan: {
            bbox: components["schemas"]["BoundingBox"];
            /** Confidence */
            confidence: number;
            /** Id */
            id: string;
            /** Source */
            source?: {
                [key: string]: number | string;
            };
            /** Text */
            text: string;
        };
        /** PublicEvaluation */
        PublicEvaluation: {
            aggregate: components["schemas"]["EvaluationAggregate"] | null;
            /** Correction Provider */
            correction_provider: string;
            /** Engine */
            engine: string;
            /** Generated From Manifest Sha256 */
            generated_from_manifest_sha256: string;
            /** Limitations */
            limitations: string[];
            /** Measured */
            measured: boolean;
            /** Methodology */
            methodology: string[];
            /** Preprocessing Profile */
            preprocessing_profile: string;
            /** Run Environment */
            run_environment: string;
            /** Samples */
            samples: components["schemas"]["EvaluationSample"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0";
        };
        /** PublicSample */
        PublicSample: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Labels */
            labels?: string[];
            /** Page Count */
            page_count: number;
            /** Preview Url */
            preview_url: string;
            /** Title */
            title: string;
        };
        /** ReportCitation */
        ReportCitation: {
            /** Block Ids */
            block_ids: string[];
            /** Page Number */
            page_number: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    get_evaluation_api_v1_evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEvaluation"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_api_v1_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_ai_correction_api_v1_jobs__job_id__ai_correction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_correction_api_v1_jobs__job_id__corrections__patch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                patch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_jobs__job_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_document_api_v1_jobs__job_id__exports__export_format__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                export_format: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_image_api_v1_jobs__job_id__pages__page_number__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                page_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_api_v1_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSample"][];
                };
            };
        };
    };
    sample_preview_api_v1_samples__sample_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
